[package]
name = "hithlain-bin"
version = "0.1.0"
edition = "2021"
description = "simple hardware descriptor language"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.34.0"
hithlain = {path="../hithlain"}
